public enum T_Typename {
    IDENFR,
    INTCON,STRCON,
    MAINTK,CONSTTK,INTTK,BREAKTK,CONTINUETK,
    IFTK,ELSETK,WHILETK,
    GETINTTK,PRINTFTK,RETURNTK,VOIDTK,
    NOT,AND,OR,
    PLUS,MINU,MULT,DIV,MOD,
    LSS,LEQ,GRE,GEQ,EQL,NEQ,ASSIGN,
    SEMICN,COMMA,LPARENT,RPARENT,
    LBRACK,RBRACK,LBRACE,RBRACE,
    EOF,NULL,SPACE
}

